### ISSUE TITLE
Question: Packagist vendor "php-mq"

### ISSUE THREAD

**Issue by hollodotme** [velkuns/php-mq#1]
Hi Romain,

I am working on a PHP message queue server / message broker based on network streams for several months now. You can see those packages here: https://github.com/php-mq

As you can see I own the github organisation `php-mq`.

Today I wanted to add one of those packages to packagist.org, but realised that you've currently taken the vendor `php-mq` on packagist.org with this repo and the composer package name `php-mq/php-mq`. 

I wanted to ask, if you would release the vendor for me and instead use `velkuns/php-mq` in your composer.json.

I order to release the vendor on packagist.org the package must be deleted there and re-added with a new vendor (changed in composer.json).

It would be awesome, if we could solve this naming conflict.

Thank you and have a nice day!
Holger

**Comment by hollodotme** [comment]
@velkuns Don't wanna bother you, but could you please respond to this issue. Thank you.

**Comment by velkuns** [comment]
Hi,

Sorry, i was in vacations.

I will change that quickly.
Sorry for the delay.

I le send you an email when it is done.

Velkuns

Le 14 août 2017 7:56 PM, Holger Woltersdorf <notifications@github.com> a écrit :

@velkuns<https://github.com/velkuns> Don't wanna bother you, but could you please respond to this issue. Thank you.

**Comment by hollodotme** [comment]
Awesome, thank you! And sorry for the noise on your vacation.

**Comment by velkuns** [comment]
Hi @hollodotme 
php-mq/php-mq has been removed from packagist. I have move my code to php-mqdb organisation.

Sorry for ce long delay, but should be ok now.

Velkuns

**Comment by hollodotme** [comment]
Hi @velkuns,

thank you so much. I registered my packages now at packagist.org.

Merci beaucoup! :D

Holger
